#pragma once
enum ImageType
{
	IMG_EVENT_TITLE,
	IMG_EVENT_ICON,
	IMG_SENTAKU_CHARACTER_NAME,
	IMG_HENSEI_CHARACTER_NAME,
	IMG_HENSEI_CHARACTER_ANOTHER_NAME,
	IMG_SYOUSAI_CHARACTER_NAME,
	IMG_DATE,
};